# Configuration Documentation: https://docs.streamlit.io/develop/api-reference/configuration/config.toml

[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s"

[client]
showErrorDetails = "full"

[runner]
magicEnabled = false
fastReruns = true
enforceSerializableSessionState = false

[server]
folderWatchBlacklist = [] # Add to later
runOnSave = true
port = 8501
maxUploadSize = 1

#[browser]
#serverAddress = "localhost"
#serverPort = 8501

[theme]
base = "dark"
# primaryColor =
# backgroundColor =